name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t pytriton_template .
      
      - name: Test Docker image
        run: |
          # Start container in background with secret passed as env
          docker run --restar=unless-stopped -d --name test_container --gpus all -p 8001:8000  pytriton_template
          
          sleep 10
          
          curl -f http://localhost:8080/health || exit 1
          